before_script:

lintDebug:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"' #只在push的时候执行
  script:
    - echo "执行成功"
    - export PUB_HOSTED_URL=https://pub.flutter-io.cn
    - export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
    - python3 --version
    - git submodule update --init # 拉取submodule
    - python3 lint_check.py ${CI_COMMIT_BRANCH} ${GITLAB_USER_NAME} #执行lint检查脚本
  tags:
    - android
    - lint